baseURL = "https://tomfeeley.com"
languageCode = "en-us"
title = "Tom Feeley"
theme = "knight"

enableRobotsTXT = true
canonifyURLs = true
disableAliases = false
googleAnalytics = "UA-108608358-1"

[params]
author = "Tom Feeley"
description = "Strategist, Designer, and Writer"
twitter = "thomasdfeeley"
email = "tom@tomfeeley.com"

[permalinks]
articles = "/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
